version: "3.9"
services:
  bjyj-ml:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    environment:
      - PYTHONUNBUFFERED=1
networks:
  bjyj_network:
    name: root_bjyj_network
    external: true
